import type {
  Persona,
  Question,
  QuizOption,
  ResponseStyle,
  TraitKey,
  TraitScores,
} from './types'

export const traitLabels: Record<TraitKey, string> = {
  vision: '格局',
  action: '行动',
  order: '秩序',
  empathy: '共情',
  insight: '洞察',
  resilience: '韧性',
}

export const responseVectors: Record<ResponseStyle, TraitScores> = {
  strategist: { vision: 5, action: 3, order: 4, empathy: 2, insight: 5, resilience: 4 },
  builder: { vision: 4, action: 4, order: 5, empathy: 3, insight: 4, resilience: 5 },
  pioneer: { vision: 4, action: 5, order: 2, empathy: 2, insight: 3, resilience: 4 },
  connector: { vision: 3, action: 3, order: 3, empathy: 5, insight: 4, resilience: 4 },
  guardian: { vision: 3, action: 4, order: 4, empathy: 5, insight: 3, resilience: 5 },
  creator: { vision: 4, action: 3, order: 2, empathy: 4, insight: 5, resilience: 3 },
  scholar: { vision: 4, action: 2, order: 4, empathy: 3, insight: 5, resilience: 4 },
  adapter: { vision: 3, action: 4, order: 3, empathy: 4, insight: 4, resilience: 5 },
}

const optionKeys = ['A', 'B', 'C', 'D'] as const
const choices = (
  ...items: ReadonlyArray<readonly [text: string, style: ResponseStyle]>
): QuizOption[] =>
  items.map(([text, style], index) => ({
    key: optionKeys[index],
    text,
    style,
  }))

export const questions: Question[] = [
  {
    id: 1,
    scene: '初入新局',
    text: '你接手一个只剩三天的棘手项目，资料混乱、所有人都在等方向。你会先做什么？',
    options: choices(
      ['找出决定成败的关键变量，再定主线', 'strategist'],
      ['列清任务、责任人和截止点，马上开工', 'builder'],
      ['先做一个能跑起来的版本，用结果破冰', 'pioneer'],
      ['逐个听完团队难处，再重新排兵布阵', 'connector'],
    ),
  },
  {
    id: 2,
    scene: '意见相左',
    text: '两个你都信任的人争得不可开交，而且各自都有道理。你更可能怎么处理？',
    options: choices(
      ['把争论拆成事实、目标和假设，逐层核对', 'scholar'],
      ['先让双方说完，找到都能接受的最小共识', 'connector'],
      ['做一个小实验，让现实替大家回答', 'adapter'],
      ['明确底线与决策规则，然后直接拍板', 'builder'],
    ),
  },
  {
    id: 3,
    scene: '旧友来信',
    text: '一位亲近的朋友请你帮忙，但这件事会打乱你本月所有计划。你会？',
    options: choices(
      ['先接住最紧急的一段，剩下的一起找办法', 'guardian'],
      ['讲清自己能做到哪里，不做超额承诺', 'builder'],
      ['先弄清他真正缺的是资源、建议还是陪伴', 'connector'],
      ['如果这件事值得，就推翻原计划全力去做', 'pioneer'],
    ),
  },
  {
    id: 4,
    scene: '窗口乍现',
    text: '一个高回报机会突然出现，信息只有六成，必须在今晚决定。你会？',
    options: choices(
      ['评估最坏代价和退出路径，再决定下注多少', 'strategist'],
      ['先占一个小位置，边走边补信息', 'adapter'],
      ['窗口比完美更重要，马上行动', 'pioneer'],
      ['继续求证关键事实，不被截止时间裹挟', 'scholar'],
    ),
  },
  {
    id: 5,
    scene: '众目之下',
    text: '你精心准备的方案被当众质疑，对方的语气并不友善。你的第一反应是？',
    options: choices(
      ['先问清具体依据，把情绪和问题分开', 'scholar'],
      ['稳住场面，会后再和关键人物谈透', 'strategist'],
      ['当场拿出核心证据，直接守住方案', 'pioneer'],
      ['先承认合理担忧，再邀请大家共同补全', 'connector'],
    ),
  },
  {
    id: 6,
    scene: '远行之前',
    text: '一场期待已久的远行临近，你通常会如何准备？',
    options: choices(
      ['路线、预算和备选方案都提前安排好', 'builder'],
      ['只定大方向，给沿途偶遇留足空间', 'creator'],
      ['研究当地历史与人文，带着问题出发', 'scholar'],
      ['先确认同行人的期待，让大家都舒服', 'connector'],
    ),
  },
  {
    id: 7,
    scene: '无人应声',
    text: '会议上抛出一个难题后，全场沉默。你通常会站到哪个位置？',
    options: choices(
      ['先给出一个不完美的起点，把局面带动起来', 'pioneer'],
      ['总结已知信息，指出真正需要回答的问题', 'strategist'],
      ['邀请最沉默的人先说，补齐被忽略的视角', 'connector'],
      ['把问题拆成几步，认领最难落地的那一段', 'guardian'],
    ),
  },
  {
    id: 8,
    scene: '骤雨将至',
    text: '计划执行到一半，外部条件突然全部改变。你最自然的动作是？',
    options: choices(
      ['快速重算优先级，保住最重要的结果', 'strategist'],
      ['先稳住团队情绪，避免忙中出错', 'guardian'],
      ['顺势换打法，把限制变成新入口', 'adapter'],
      ['暂停扩张，重新建立流程与检查点', 'builder'],
    ),
  },
  {
    id: 9,
    scene: '旧法失灵',
    text: '一个过去屡试不爽的方法突然失效，你会怎么理解这件事？',
    options: choices(
      ['环境变了，应该重新定义问题', 'creator'],
      ['先复盘执行偏差，不急着推翻方法', 'builder'],
      ['找反例和新证据，更新自己的判断', 'scholar'],
      ['没有必须守的打法，换一条路继续推进', 'adapter'],
    ),
  },
  {
    id: 10,
    scene: '案牍如山',
    text: '事情多到明显做不完时，你最可能优先放下哪一种？',
    options: choices(
      ['重要但还不紧急、暂时不会失控的事', 'strategist'],
      ['可以交给别人，并且能明确验收的事', 'builder'],
      ['只是为了证明自己、并不真正重要的事', 'creator'],
      ['对别人影响最小、可以晚一点回应的事', 'guardian'],
    ),
  },
  {
    id: 11,
    scene: '并肩之人',
    text: '选择长期合作伙伴时，你最看重什么？',
    options: choices(
      ['判断清醒，能看见三步之后', 'strategist'],
      ['说到做到，困难时依然可靠', 'guardian'],
      ['彼此启发，总能生出新想法', 'creator'],
      ['沟通坦诚，分歧也能好好说', 'connector'],
    ),
  },
  {
    id: 12,
    scene: '岔路当前',
    text: '两条路摆在眼前：一条稳妥清晰，一条未知但可能打开新世界。你会？',
    options: choices(
      ['比较长期上限，而不是只看眼前风险', 'strategist'],
      ['选择稳妥路，把已有积累做深', 'builder'],
      ['去未知那条，真正想走比确定更重要', 'creator'],
      ['先用业余时间试走一段，再决定切换', 'adapter'],
    ),
  },
  {
    id: 13,
    scene: '功成之后',
    text: '一件大事终于完成，大家都在庆祝。你最想做的是？',
    options: choices(
      ['安静复盘：这次真正赢在哪里', 'scholar'],
      ['把功劳说清楚，让每个参与者都被看见', 'connector'],
      ['趁势开启下一站，不让能量散掉', 'pioneer'],
      ['把有效做法沉淀下来，让下次更轻松', 'builder'],
    ),
  },
  {
    id: 14,
    scene: '原则与人情',
    text: '你认定的原则会让在意的人失望。面对这种冲突，你会？',
    options: choices(
      ['守住原则，同时认真解释它为何重要', 'guardian'],
      ['回到原则背后的目的，寻找第三种做法', 'strategist'],
      ['关系不是规则题，愿意为重要的人调整', 'connector'],
      ['先独处想清楚，确保不是在被情绪推动', 'scholar'],
    ),
  },
  {
    id: 15,
    scene: '陌生席间',
    text: '走进一个几乎谁也不认识的场合，你通常会？',
    options: choices(
      ['观察谁在影响气氛，先读懂场域', 'strategist'],
      ['主动和身边人打招呼，很快建立连接', 'connector'],
      ['寻找最有趣的话题，跟着好奇心走', 'creator'],
      ['找一件能帮上忙的事，自然进入角色', 'guardian'],
    ),
  },
  {
    id: 16,
    scene: '最后一夜',
    text: '截止时间就在明早，作品还有很多地方可以更好。你会？',
    options: choices(
      ['锁定交付线，先确保完整可用', 'builder'],
      ['保住最有辨识度的部分，其余从简', 'creator'],
      ['快速请目标用户看一遍，只改关键问题', 'adapter'],
      ['继续打磨逻辑，宁可牺牲一些形式', 'scholar'],
    ),
  },
  {
    id: 17,
    scene: '流言四起',
    text: '关于你的误解正在扩散，但回应也可能让它更受关注。你会？',
    options: choices(
      ['只向关键关系说明，不追着所有人解释', 'strategist'],
      ['公开事实和边界，简短回应一次', 'builder'],
      ['先理解大家为何愿意相信，再决定入口', 'connector'],
      ['用接下来的行动给出答案，不参与拉扯', 'guardian'],
    ),
  },
  {
    id: 18,
    scene: '强者同行',
    text: '你遇到一个能力很强、风格却与你完全不同的人。你更可能？',
    options: choices(
      ['明确分工，用差异组成更强的系统', 'builder'],
      ['研究他的思路，看看自己哪里可以更新', 'scholar'],
      ['先一起做个小项目，边配合边磨合', 'adapter'],
      ['被差异点燃，想和他碰撞出新东西', 'creator'],
    ),
  },
  {
    id: 19,
    scene: '生活节拍',
    text: '哪一种日常最容易让你感到“我正在好好生活”？',
    options: choices(
      ['目标清楚，每天都在靠近长期方向', 'strategist'],
      ['规律可靠，手上的事一件件完成', 'builder'],
      ['有新鲜体验，也有表达和创造的空间', 'creator'],
      ['和在意的人保持真实而温暖的连接', 'connector'],
    ),
  },
  {
    id: 20,
    scene: '一封长信',
    text: '如果只能给五年前的自己一句提醒，你最想写下哪句？',
    options: choices(
      ['别只顾眼前，很多选择要看更长的线', 'strategist'],
      ['别怕开始，答案往往在行动之后', 'pioneer'],
      ['不必一直坚强，允许别人靠近你', 'guardian'],
      ['你不必活成标准答案，诚实一点', 'creator'],
    ),
  },
  {
    id: 21,
    scene: '士气低落',
    text: '团队连续受挫，大家开始怀疑目标。你会如何重新点火？',
    options: choices(
      ['重讲为什么出发，让大家看见目标的意义', 'guardian'],
      ['拿下一个最小胜利，让信心从结果里回来', 'pioneer'],
      ['调整路径和分工，降低无效消耗', 'builder'],
      ['坦诚讨论是否还值得继续，不强行鼓舞', 'connector'],
    ),
  },
  {
    id: 22,
    scene: '难题无解',
    text: '一个问题想了很久仍无解，你通常如何打破停滞？',
    options: choices(
      ['换一个尺度或视角，重新描述问题', 'creator'],
      ['找相关领域的规律，建立新的解释模型', 'scholar'],
      ['先做最小动作，让反馈带来新信息', 'adapter'],
      ['暂时放下，去处理能推进的部分', 'builder'],
    ),
  },
  {
    id: 23,
    scene: '留名于世',
    text: '如果许多年后别人提起你，你最希望他们记住什么？',
    options: choices(
      ['在关键时刻做过清醒的决定', 'strategist'],
      ['把值得的事情真正建了起来', 'builder'],
      ['给别人带去过勇气、照顾或希望', 'guardian'],
      ['活得真诚，并留下独特的表达', 'creator'],
    ),
  },
  {
    id: 24,
    scene: '执笔落款',
    text: '把你的人生写成一卷未完的史书，此刻最像哪一行题记？',
    options: choices(
      ['心中有图，落子有声', 'strategist'],
      ['积微成著，久久为功', 'builder'],
      ['路远不惧，逢山开道', 'pioneer'],
      ['见人见己，守心向前', 'connector'],
    ),
  },
]

export const personas: Persona[] = [
  {
    id: 'wang-yangming',
    name: '王阳明',
    era: '明',
    title: '知行合一的破题者',
    seal: '知行',
    quote: '看见本质之后，你更愿意让答案在行动里成立。',
    profile: { vision: 91, action: 87, order: 76, empathy: 69, insight: 98, resilience: 92 },
    tags: ['洞察', '实践', '定力'],
    portrait: '明',
    summary: '你善于从混乱里找到真正的问题，也很难满足于只“想明白”。当方向确定，你会把认知一步步压进现实，让复杂的局重新变得清楚。',
    gift: '把思考与行动接在一起，是你最鲜明的力量。别人还在争论表象时，你已经在寻找可以验证的下一步。',
    shadow: '越能看透，越容易对自己要求过高。偶尔你会把“还没做到”误判成“还没想透”，于是继续推演，忘了给自己一点试错空间。',
    action: '选一件最近反复思考的事，把它缩成一个 30 分钟内能完成的动作，今天就让答案落地。',
  },
  {
    id: 'wu-zetian',
    name: '武则天',
    era: '唐',
    title: '重写规则的掌局者',
    seal: '势',
    quote: '你不等待位置被让出，更擅长亲手建立新秩序。',
    profile: { vision: 95, action: 92, order: 96, empathy: 55, insight: 88, resilience: 98 },
    tags: ['格局', '决断', '秩序'],
    portrait: '曌',
    summary: '你对局势、资源和位置有天然敏感度。面对复杂关系，你很少只看眼前输赢，而会思考怎样让主动权长期留在自己手里。',
    gift: '你能在噪音里抓住权力与责任真正流向哪里，并迅速搭出一套可执行的秩序。',
    shadow: '当安全感过度依赖掌控，身边的人可能只给你结果，不再给你真话。强大也需要反馈回路。',
    action: '挑一件你正在主导的事，主动邀请一位可信的人只提盲点，不解释、不反驳，先完整听完。',
  },
  {
    id: 'su-shi',
    name: '苏轼',
    era: '宋',
    title: '把风雨酿成旷达的人',
    seal: '旷',
    quote: '世界给你起伏，你总能慢慢把它过成新的风景。',
    profile: { vision: 84, action: 68, order: 48, empathy: 88, insight: 87, resilience: 99 },
    tags: ['旷达', '创造', '韧性'],
    portrait: '轼',
    summary: '你既能感受生活的重量，也有把重量化开的本事。环境改变时，你不会否认难处，却常能重新找到趣味、表达和继续走下去的理由。',
    gift: '你的恢复力不是遗忘，而是把经历放进更大的坐标。你也常用幽默和温度，让身边的人重新松一口气。',
    shadow: '看似什么都能消化，有时会让别人忽略你的疲惫。真正的豁达也包括承认：这一刻我需要被照顾。',
    action: '为最近一件不顺写下三个版本：事实、感受、它可能带来的新入口。然后只选一个入口去试。',
  },
  {
    id: 'li-qingzhao',
    name: '李清照',
    era: '宋',
    title: '将细微感受写成光的人',
    seal: '清',
    quote: '你能听见情绪里最轻的回声，也愿意忠于真实。',
    profile: { vision: 70, action: 55, order: 51, empathy: 99, insight: 92, resilience: 79 },
    tags: ['敏锐', '真诚', '表达'],
    portrait: '词',
    summary: '你对关系、氛围与细节的变化非常敏感。许多人说不清的感受，到你这里往往能被准确辨认，也能被转化成有分量的表达。',
    gift: '细腻并不等于脆弱。你的感受力让你更接近真实，也让别人感到自己被认真看见。',
    shadow: '你容易把外界的波动留在心里反复回放。共情太满时，别人的情绪会悄悄占据本属于你的空间。',
    action: '今天记录一次情绪波动，并写两列：哪些属于我，哪些属于别人。只处理第一列。',
  },
  {
    id: 'zhang-qian',
    name: '张骞',
    era: '汉',
    title: '向未知开路的远行者',
    seal: '拓',
    quote: '你相信路不是等来的，而是一步一步走通的。',
    profile: { vision: 96, action: 94, order: 65, empathy: 74, insight: 81, resilience: 100 },
    tags: ['开拓', '行动', '耐力'],
    portrait: '骞',
    summary: '陌生不会让你退缩，反而容易点燃你的探索欲。你看重的不只是抵达，而是建立一条后来者也能走的通路。',
    gift: '你能在不确定里维持方向，失败和绕路很难真正让你停下。你的行动常会把原本隔开的世界连接起来。',
    shadow: '一直向外开拓，容易忘记回收经验与体力。路走得很远，不等于每一段都已经变成你的积累。',
    action: '为正在探索的一件事设一个“收口日”：整理成果、删掉无效路线，再决定下一段往哪里走。',
  },
  {
    id: 'mozi',
    name: '墨子',
    era: '战国',
    title: '把理想做成器物的人',
    seal: '兼',
    quote: '你的关心不止停在态度，更想变成真正有用的办法。',
    profile: { vision: 89, action: 89, order: 91, empathy: 96, insight: 87, resilience: 93 },
    tags: ['务实', '仁心', '方法'],
    portrait: '墨',
    summary: '你很难对真实的问题视而不见。相比漂亮口号，你更在意方法是否有效、资源是否节制、结果是否真的让更多人受益。',
    gift: '理想与工程能力在你身上并不冲突。你既愿意关心人，也愿意为这份关心搭出可重复的解决方案。',
    shadow: '长期把“有用”放在第一位，可能让你忽略自己的感受与审美。不是所有价值都必须立刻证明。',
    action: '找一个你真正在意的问题，不做宏大计划，只设计一个本周能帮助到具体一人的小方案。',
  },
  {
    id: 'hua-mulan',
    name: '花木兰',
    era: '北朝',
    title: '关键时刻站出来的人',
    seal: '勇',
    quote: '当责任真正落到眼前，你往往比自己想象得更勇敢。',
    profile: { vision: 77, action: 100, order: 75, empathy: 84, insight: 72, resilience: 98 },
    tags: ['担当', '果敢', '适应'],
    portrait: '兰',
    summary: '你不一定总抢在最前面，但真正需要有人承担时，你很难袖手旁观。进入陌生环境后，你也能迅速学习规则并找到自己的位置。',
    gift: '你的勇气很具体：不是等待害怕消失，而是带着害怕把该做的事做完。',
    shadow: '习惯扛住一切，会让疲惫来得很晚、很重。能承担不代表每一次都必须独自承担。',
    action: '写下目前最耗力的一件事，明确其中哪 20% 可以交出去，并在今天发出一次具体求助。',
  },
  {
    id: 'zhang-liang',
    name: '张良',
    era: '汉',
    title: '在棋局之外看棋的人',
    seal: '谋',
    quote: '你不急着成为场上最响的人，更在意哪一步真正改变全局。',
    profile: { vision: 98, action: 70, order: 85, empathy: 71, insight: 100, resilience: 89 },
    tags: ['谋略', '洞察', '取舍'],
    portrait: '良',
    summary: '你善于把自己从眼前情绪里抽离，观察局势如何形成、资源如何流动，以及什么时候出手最有价值。',
    gift: '你很少把力气平均分配，而会寻找真正的杠杆点。复杂问题到了你这里，常能被重新排出轻重缓急。',
    shadow: '等待最好时机可能演变成延迟行动。现实中的窗口很少完美，有些信息只有入局以后才会出现。',
    action: '为一个正在等待的决定设“七成阈值”：信息达到七成就做最小动作，不再继续空想。',
  },
  {
    id: 'tao-yuanming',
    name: '陶渊明',
    era: '晋',
    title: '忠于内在尺度的人',
    seal: '真',
    quote: '你不轻易把人生交给热闹，更愿意守住自己的节奏。',
    profile: { vision: 76, action: 54, order: 47, empathy: 85, insight: 93, resilience: 84 },
    tags: ['自洽', '清醒', '从容'],
    portrait: '陶',
    summary: '你对“什么值得”有一套内在标准。外界的认可当然可贵，但它很难长期压过你对真实、自由和生活质感的需要。',
    gift: '你有从喧闹里退一步的能力，不会轻易用别人的速度定义自己。这份自洽让你拥有难得的精神余地。',
    shadow: '退出不适合的竞争是清醒，但也要留意：有时你是在守心，有时只是害怕主动争取。',
    action: '挑一个你真心想要、却一直说“随缘”的目标，做一次不违背本心的主动争取。',
  },
  {
    id: 'zhuge-liang',
    name: '诸葛亮',
    era: '三国',
    title: '让复杂系统持续运转的人',
    seal: '谨',
    quote: '你习惯把责任接稳，再让混乱一步步变得有序。',
    profile: { vision: 91, action: 86, order: 100, empathy: 77, insight: 97, resilience: 96 },
    tags: ['系统', '责任', '长期'],
    portrait: '亮',
    summary: '你擅长把庞杂信息变成计划，把遥远目标拆成一连串可执行的节点。别人信任你，往往不是因为你说得响，而是因为你总能把事情托住。',
    gift: '你把可靠做成了一种系统能力：不只解决一次问题，还会思考怎样让同类问题不再反复发生。',
    shadow: '责任感过强时，你容易成为所有流程的最后一道保险。系统越依赖你，你越难真正休息。',
    action: '选一项只有你会做的工作，把它写成三步说明并交给另一个人试一次，让可靠不再等于亲力亲为。',
  },
]
